In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model
from math import sqrt
from sklearn.metrics import mean_squared_error

In [2]:
df = pd.read_csv("D:/Study/MCA/4th Sem/DA/csv/Housing.csv")
df.head()

Unnamed: 0    price  lotsize  bedrooms  bathrms  stories driveway recroom  \
0           1  42000.0     5850         3        1        2      yes      no   
1           2  38500.0     4000         2        1        1      yes      no   
2           3  49500.0     3060         3        1        1      yes      no   
3           4  60500.0     6650         3        1        2      yes     yes   
4           5  61000.0     6360         2        1        1      yes      no   

  fullbase gashw airco  garagepl prefarea  
0      yes    no    no         1       no  
1       no    no    no         0       no  
2       no    no    no         0       no  
3       no    no    no         0       no  
4       no    no    no         0       no

In [7]:
df.columns

Index(['Unnamed: 0', 'price', 'lotsize', 'bedrooms', 'bathrms', 'stories',
       'driveway', 'recroom', 'fullbase', 'gashw', 'airco', 'garagepl',
       'prefarea'],
      dtype='object')

In [5]:
df.tail()

Unnamed: 0     price  lotsize  bedrooms  bathrms  stories driveway  \
541         542   91500.0     4800         3        2        4      yes   
542         543   94000.0     6000         3        2        4      yes   
543         544  103000.0     6000         3        2        4      yes   
544         545  105000.0     6000         3        2        2      yes   
545         546  105000.0     6000         3        1        2      yes   

    recroom fullbase gashw airco  garagepl prefarea  
541     yes       no    no   yes         0       no  
542      no       no    no   yes         0       no  
543     yes       no    no   yes         1       no  
544     yes       no    no   yes         1       no  
545      no       no    no   yes         1       no

In [13]:
# What is that you want to predict
# when y is numerical, then apply regression
# when y is categorical, then apply classification
# y = f(x) where x is 1, then it is single linear regression - one attribute
# y = f(x) where x is >1, then it is mutliple linear regression - multiple attributes
y = df['price']
print(type(y))
y = y.values
y = y.reshape(len(y), 1)
print(y)

<class 'pandas.core.series.Series'>
[[ 42000.]
 [ 38500.]
 [ 49500.]
 [ 60500.]
 [ 61000.]
 [ 66000.]
 [ 66000.]
 [ 69000.]
 [ 83800.]
 [ 88500.]
 [ 90000.]
 [ 30500.]
 [ 27000.]
 [ 36000.]
 [ 37000.]
 [ 37900.]
 [ 40500.]
 [ 40750.]
 [ 45000.]
 [ 45000.]
 [ 48500.]
 [ 65900.]
 [ 37900.]
 [ 38000.]
 [ 42000.]
 [ 42300.]
 [ 43500.]
 [ 44000.]
 [ 44500.]
 [ 44900.]
 [ 45000.]
 [ 48000.]
 [ 49000.]
 [ 51500.]
 [ 61000.]
 [ 61000.]
 [ 61700.]
 [ 67000.]
 [ 82000.]
 [ 54500.]
 [ 66500.]
 [ 70000.]
 [ 82000.]
 [ 92000.]
 [ 38000.]
 [ 44000.]
 [ 41000.]
 [ 43000.]
 [ 48000.]
 [ 54800.]
 [ 55000.]
 [ 57000.]
 [ 68000.]
 [ 95000.]
 [ 38000.]
 [ 25000.]
 [ 25245.]
 [ 56000.]
 [ 35500.]
 [ 30000.]
 [ 48000.]
 [ 48000.]
 [ 52000.]
 [ 54000.]
 [ 56000.]
 [ 60000.]
 [ 60000.]
 [ 67000.]
 [ 47000.]
 [ 70000.]
 [ 45000.]
 [ 51000.]
 [ 32500.]
 [ 34000.]
 [ 35000.]
 [ 36000.]
 [ 45000.]
 [ 47000.]
 [ 55000.]
 [ 63900.]
 [ 50000.]
 [ 35000.]
 [ 50000.]
 [ 43000.]
 [ 55500.]
 [ 57000.]
 [ 60000.]
 [ 7800

In [14]:
x = df['lotsize']
x = x.values
x = x.reshape(len(x), 1)
print(x)

[[ 5850]
 [ 4000]
 [ 3060]
 [ 6650]
 [ 6360]
 [ 4160]
 [ 3880]
 [ 4160]
 [ 4800]
 [ 5500]
 [ 7200]
 [ 3000]
 [ 1700]
 [ 2880]
 [ 3600]
 [ 3185]
 [ 3300]
 [ 5200]
 [ 3450]
 [ 3986]
 [ 4785]
 [ 4510]
 [ 4000]
 [ 3934]
 [ 4960]
 [ 3000]
 [ 3800]
 [ 4960]
 [ 3000]
 [ 4500]
 [ 3500]
 [ 3500]
 [ 4000]
 [ 4500]
 [ 6360]
 [ 4500]
 [ 4032]
 [ 5170]
 [ 5400]
 [ 3150]
 [ 3745]
 [ 4520]
 [ 4640]
 [ 8580]
 [ 2000]
 [ 2160]
 [ 3040]
 [ 3090]
 [ 4960]
 [ 3350]
 [ 5300]
 [ 4100]
 [ 9166]
 [ 4040]
 [ 3630]
 [ 3620]
 [ 2400]
 [ 7260]
 [ 4400]
 [ 2400]
 [ 4120]
 [ 4750]
 [ 4280]
 [ 4820]
 [ 5500]
 [ 5500]
 [ 5040]
 [ 6000]
 [ 2500]
 [ 4095]
 [ 4095]
 [ 3150]
 [ 1836]
 [ 2475]
 [ 3210]
 [ 3180]
 [ 1650]
 [ 3180]
 [ 3180]
 [ 6360]
 [ 4240]
 [ 3240]
 [ 3650]
 [ 3240]
 [ 3780]
 [ 6480]
 [ 5850]
 [ 3150]
 [ 3000]
 [ 3090]
 [ 6060]
 [ 5900]
 [ 7420]
 [ 8500]
 [ 8050]
 [ 6800]
 [ 8250]
 [ 8250]
 [ 3500]
 [ 2835]
 [ 4500]
 [ 3300]
 [ 4320]
 [ 3500]
 [ 4992]
 [ 4600]
 [ 3720]
 [ 3680]
 [ 3000]
 [ 3750]
 [ 5076]
 

In [42]:
# categorical - classification --> Accuracy rate is found
# numerical - regression --> Error rate is found
x_train = x[:430]
x_test = x[431:]
y_train = y[:430]
y_test = y[431:]
regr = linear_model.LinearRegression()
regr.fit(x_train, y_train)
pred = regr.predict(x_test)
print(pred)

[[ 61800.15458669]
 [ 70338.56322064]
 [ 92620.519929  ]
 [ 91169.11312677]
 [ 70538.31111012]
 [ 89945.54218586]
 [ 52045.76273613]
 [ 74695.02911249]
 [ 82834.52720112]
 [ 56682.41462985]
 [ 52735.89547336]
 [ 44004.3043674 ]
 [ 71674.68054429]
 [ 61785.80346805]
 [103486.13576193]
 [102602.77979221]
 [ 86002.6459268 ]
 [ 69059.15826549]
 [ 60051.68936128]
 [ 48339.58963432]
 [ 48840.05364112]
 [ 57985.59935321]
 [ 74512.57486169]
 [ 57714.64402403]
 [ 59902.16771077]
 [ 66597.67061759]
 [ 96274.06707275]
 [ 37924.06678055]
 [ 44594.49118362]
 [ 44594.49118362]
 [ 52635.94955234]
 [ 47114.37574501]
 [ 58243.76867153]
 [ 52635.94955234]
 [ 53340.43340822]
 [ 56488.93433331]
 [ 43890.00732774]
 [ 42580.48973561]
 [ 53441.02983872]
 [ 58975.00468357]
 [ 40032.09924159]
 [103469.18550001]
 [ 76899.84643792]
 [ 77157.40684334]
 [ 82047.19392215]
 [ 85228.05477867]
 [ 82118.2489372 ]
 [ 71351.17709767]
 [ 77156.1072717 ]
 [ 75708.5991844 ]
 [ 68496.0669822 ]
 [ 97343.53727084]
 [ 44423.481

In [43]:
rms = sqrt(mean_squared_error(y_test, pred))
print(rms)

16809.856315522105


# Multiple Linear Regression

In [ ]:
# Data processing on Housing data

In [28]:
degree = [1,2,3]
x = df['lotsize']
lt = pd.cut(x, 3, labels = degree)
print(lt)

0      1
1      1
2      1
3      2
4      1
5      1
6      1
7      1
8      1
9      1
10     2
11     1
12     1
13     1
14     1
15     1
16     1
17     1
18     1
19     1
20     1
21     1
22     1
23     1
24     1
25     1
26     1
27     1
28     1
29     1
      ..
516    1
517    1
518    1
519    1
520    2
521    1
522    1
523    1
524    1
525    2
526    1
527    1
528    1
529    1
530    1
531    2
532    3
533    2
534    1
535    1
536    1
537    1
538    1
539    2
540    2
541    1
542    1
543    1
544    1
545    1
Name: lotsize, Length: 546, dtype: category
Categories (3, int64): [1 < 2 < 3]


In [33]:
df['lt'] = lt
x = df[['lt', 'bedrooms']]
print(x)

    lt  bedrooms
0    1         3
1    1         2
2    1         3
3    2         3
4    1         2
5    1         3
6    1         3
7    1         3
8    1         3
9    1         3
10   2         3
11   1         2
12   1         3
13   1         3
14   1         2
15   1         2
16   1         3
17   1         4
18   1         1
19   1         2
20   1         3
21   1         4
22   1         3
23   1         2
24   1         2
25   1         2
26   1         2
27   1         2
28   1         3
29   1         3
..  ..       ...
516  1         3
517  1         4
518  1         4
519  1         3
520  2         4
521  1         4
522  1         4
523  1         4
524  1         4
525  2         3
526  1         3
527  1         3
528  1         3
529  1         3
530  1         3
531  2         3
532  3         3
533  2         3
534  1         3
535  1         3
536  1         3
537  1         3
538  1         3
539  2         4
540  2         3
541  1         3
542  1        

# MLS - Data Processing -> Categorical to Numerical

In [37]:
from sklearn.preprocessing import LabelEncoder # classname
number = LabelEncoder() # constructor
df['prefarea'] = number.fit_transform(df['prefarea'].astype('str'))
df[''] = number
print(df['prefarea'])

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
      ..
516    0
517    0
518    0
519    0
520    0
521    0
522    0
523    0
524    0
525    0
526    0
527    0
528    0
529    0
530    0
531    0
532    0
533    0
534    0
535    0
536    0
537    0
538    0
539    0
540    0
541    0
542    0
543    0
544    0
545    0
Name: prefarea, Length: 546, dtype: int32


In [41]:
# Dimensional reductional methods
# using PCA
from sklearn import decomposition
pca = decomposition.PCA(n_components = 1)
x = df[['lotsize', 'bedrooms', 'bathrms', 'stories', 'garagepl']]
principalComponents = pca.fit_transform(x)
print(principalComponents)

[[ 6.99734462e+02]
 [-1.15026574e+03]
 [-2.09026568e+03]
 [ 1.49973431e+03]
 [ 1.20973423e+03]
 [-9.90265690e+02]
 [-1.27026533e+03]
 [-9.90265623e+02]
 [-3.50265698e+02]
 [ 3.49734578e+02]
 [ 2.04973474e+03]
 [-2.15026573e+03]
 [-3.45026563e+03]
 [-2.27026567e+03]
 [-1.55026573e+03]
 [-1.96526573e+03]
 [-1.85026551e+03]
 [ 4.97344151e+01]
 [-1.70026578e+03]
 [-1.16426555e+03]
 [-3.65265525e+02]
 [-6.40265565e+02]
 [-1.15026565e+03]
 [-1.21626574e+03]
 [-1.90265752e+02]
 [-2.15026569e+03]
 [-1.35026574e+03]
 [-1.90265752e+02]
 [-2.15026568e+03]
 [-6.50265661e+02]
 [-1.65026573e+03]
 [-1.65026532e+03]
 [-1.15026574e+03]
 [-6.50265746e+02]
 [ 1.20973426e+03]
 [-6.50265466e+02]
 [-1.11826574e+03]
 [ 1.97343974e+01]
 [ 2.49734704e+02]
 [-2.00026568e+03]
 [-1.40526565e+03]
 [-6.30265661e+02]
 [-5.10265471e+02]
 [ 3.42973476e+03]
 [-3.15026568e+03]
 [-2.99026563e+03]
 [-2.11026573e+03]
 [-2.06026564e+03]
 [-1.90265582e+02]
 [-1.80026565e+03]
 [ 1.49734477e+02]
 [-1.05026564e+03]
 [ 4.0157344

In [44]:
df['pca1'] = principalComponents
x = df['pca1']
x = x.values
x = x.reshape(len(x), 1)
print(x)

[[ 6.99734462e+02]
 [-1.15026574e+03]
 [-2.09026568e+03]
 [ 1.49973431e+03]
 [ 1.20973423e+03]
 [-9.90265690e+02]
 [-1.27026533e+03]
 [-9.90265623e+02]
 [-3.50265698e+02]
 [ 3.49734578e+02]
 [ 2.04973474e+03]
 [-2.15026573e+03]
 [-3.45026563e+03]
 [-2.27026567e+03]
 [-1.55026573e+03]
 [-1.96526573e+03]
 [-1.85026551e+03]
 [ 4.97344151e+01]
 [-1.70026578e+03]
 [-1.16426555e+03]
 [-3.65265525e+02]
 [-6.40265565e+02]
 [-1.15026565e+03]
 [-1.21626574e+03]
 [-1.90265752e+02]
 [-2.15026569e+03]
 [-1.35026574e+03]
 [-1.90265752e+02]
 [-2.15026568e+03]
 [-6.50265661e+02]
 [-1.65026573e+03]
 [-1.65026532e+03]
 [-1.15026574e+03]
 [-6.50265746e+02]
 [ 1.20973426e+03]
 [-6.50265466e+02]
 [-1.11826574e+03]
 [ 1.97343974e+01]
 [ 2.49734704e+02]
 [-2.00026568e+03]
 [-1.40526565e+03]
 [-6.30265661e+02]
 [-5.10265471e+02]
 [ 3.42973476e+03]
 [-3.15026568e+03]
 [-2.99026563e+03]
 [-2.11026573e+03]
 [-2.06026564e+03]
 [-1.90265582e+02]
 [-1.80026565e+03]
 [ 1.49734477e+02]
 [-1.05026564e+03]
 [ 4.0157344

In [45]:
from sklearn.preprocessing import MinMaxScaler
df = pd.read_csv("D:/Study/MCA/4th Sem/DA/csv/Housing.csv");
df.head()
lot = df[['lotsize']]
scaler = MinMaxScaler(feature_range = (0,1))
rescaledlot = scaler.fit_transform(lot)
df['rlot'] = rescaledlot
X = df[['rlot', 'bedrooms', 'bathrms', 'stories', 'garagepl']]
X.head()

C:\Anaconda\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


rlot  bedrooms  bathrms  stories  garagepl
0  0.288660         3        1        2         1
1  0.161512         2        1        1         0
2  0.096907         3        1        1         0
3  0.343643         3        1        2         0
4  0.323711         2        1        1         0