## Support Vector Machine Classification

Import the Redwine Dataset. You are supposed to estimate the redwine quality as the outcome variable.
Do Standard scaling on the train dataset and learn the model using SVM classifier. 
Perform a Grid Serach and find the best parameters of C and Gamma.
Visualize the classification boundary
Evaluate the model using the suitable performance metrics

In [98]:
import pandas as pd
import numpy as np
df = pd.read_csv('D:/Study/MCA/5thSem/ML/ML/Redwine.csv', sep=';')
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [99]:
df.keys()

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [100]:
x = df.drop(['quality'],axis=1)
y = df['quality']

In [101]:
from sklearn import svm
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [102]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.4)

In [103]:
from sklearn.preprocessing import StandardScaler

In [104]:
scaler = StandardScaler().fit(x_train)
standardised_x = scaler.transform(x_train)
standardised_y = scaler.transform(x_test)
print(standardised_x)
print(standardised_y)

[[-0.22415264 -1.05691165  0.47958225 ... -0.28393678 -0.69499597
   0.71841783]
 [-0.33969275 -1.3848067   0.16987223 ... -0.21762032  1.4248062
   0.8109851 ]
 [ 0.52685809  2.11274057 -0.13983779 ...  1.10870882 -0.69499597
  -0.57752383]
 ...
 [-0.97516337  1.45695045 -1.22382285 ...  1.37397465 -0.93052954
   1.64409045]
 [ 0.23800781  0.91045869 -0.13983779 ...  0.0476455  -0.34169561
  -1.31806193]
 [ 1.45117899 -0.45577071  0.32472724 ... -0.48288615  0.30602172
   0.34814879]]
[[-0.57077297  1.07440622 -0.13983779 ... -0.35025324 -0.400579
  -1.04036014]
 [ 1.62448916 -1.00226247  1.09900228 ... -0.94710135 -0.75387936
   0.070447  ]
 [-0.74408314 -0.61971824 -0.39792947 ...  0.5118607  -0.57722918
   0.44071605]
 ...
 [ 0.29577787 -1.43945588  0.99576561 ... -0.35025324 -0.57722918
   0.8109851 ]
 [-0.3974628  -0.23717401 -0.03660111 ... -1.34500009  0.83597227
  -1.04036014]
 [ 0.29577787 -1.27550835  0.58281892 ...  0.5118607   0.36490512
   1.2738214 ]]


# Building the model

In [105]:
from sklearn.svm import SVC
model = SVC()
model.fit(x_train,y_train)

C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [106]:
predictions = model.predict(x_test)

In [107]:
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [0.1, 1, 10, 100, 1000], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001], 'kernel': ['rbf']}
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3, cv = 9)
grid.fit(x_train, y_train)

Fitting 9 folds for each of 25 candidates, totalling 225 fits
[CV] C=0.1, gamma=1, kernel=rbf ......................................


C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=9.
  % (min_groups, self.n_splits)), Warning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.413, total=   0.2s
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s


[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.417, total=   0.2s
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.3s remaining:    0.0s


[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.417, total=   0.2s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.417, total=   0.2s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.421, total=   0.2s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.425, total=   0.2s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.429, total=   0.3s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.433, total=   0.2s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.433, total=   0.2s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] .

[CV] .......... C=1, gamma=0.1, kernel=rbf, score=0.587, total=   0.1s
[CV] C=1, gamma=0.1, kernel=rbf ......................................
[CV] .......... C=1, gamma=0.1, kernel=rbf, score=0.587, total=   0.1s
[CV] C=1, gamma=0.01, kernel=rbf .....................................
[CV] ......... C=1, gamma=0.01, kernel=rbf, score=0.440, total=   0.1s
[CV] C=1, gamma=0.01, kernel=rbf .....................................
[CV] ......... C=1, gamma=0.01, kernel=rbf, score=0.500, total=   0.1s
[CV] C=1, gamma=0.01, kernel=rbf .....................................
[CV] ......... C=1, gamma=0.01, kernel=rbf, score=0.546, total=   0.1s
[CV] C=1, gamma=0.01, kernel=rbf .....................................
[CV] ......... C=1, gamma=0.01, kernel=rbf, score=0.472, total=   0.1s
[CV] C=1, gamma=0.01, kernel=rbf .....................................
[CV] ......... C=1, gamma=0.01, kernel=rbf, score=0.449, total=   0.1s
[CV] C=1, gamma=0.01, kernel=rbf .....................................
[CV] .

[CV] ....... C=10, gamma=0.001, kernel=rbf, score=0.528, total=   0.1s
[CV] C=10, gamma=0.001, kernel=rbf ...................................
[CV] ....... C=10, gamma=0.001, kernel=rbf, score=0.533, total=   0.1s
[CV] C=10, gamma=0.001, kernel=rbf ...................................
[CV] ....... C=10, gamma=0.001, kernel=rbf, score=0.575, total=   0.1s
[CV] C=10, gamma=0.001, kernel=rbf ...................................
[CV] ....... C=10, gamma=0.001, kernel=rbf, score=0.543, total=   0.1s
[CV] C=10, gamma=0.001, kernel=rbf ...................................
[CV] ....... C=10, gamma=0.001, kernel=rbf, score=0.577, total=   0.1s
[CV] C=10, gamma=0.001, kernel=rbf ...................................
[CV] ....... C=10, gamma=0.001, kernel=rbf, score=0.587, total=   0.1s
[CV] C=10, gamma=0.0001, kernel=rbf ..................................
[CV] ...... C=10, gamma=0.0001, kernel=rbf, score=0.468, total=   0.1s
[CV] C=10, gamma=0.0001, kernel=rbf ..................................
[CV] .

[CV] ..... C=100, gamma=0.0001, kernel=rbf, score=0.615, total=   0.2s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV] ......... C=1000, gamma=1, kernel=rbf, score=0.495, total=   0.2s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV] ......... C=1000, gamma=1, kernel=rbf, score=0.565, total=   0.2s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV] ......... C=1000, gamma=1, kernel=rbf, score=0.500, total=   0.2s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV] ......... C=1000, gamma=1, kernel=rbf, score=0.528, total=   0.2s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV] ......... C=1000, gamma=1, kernel=rbf, score=0.486, total=   0.2s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV] ......... C=1000, gamma=1, kernel=rbf, score=0.481, total=   0.2s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV] .

[Parallel(n_jobs=1)]: Done 225 out of 225 | elapsed:   36.0s finished
C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=9, error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [108]:
grid.best_params_

{'C': 1000, 'gamma': 0.001, 'kernel': 'rbf'}

In [109]:
grid.best_estimator_

SVC(C=1000, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [110]:
grid_predictions = grid.predict(x_test)
print(grid_predictions)

[5 5 6 5 5 7 6 7 5 5 6 5 7 5 5 6 5 5 5 5 5 5 6 6 5 5 6 5 5 5 6 5 5 5 7 6 6
 5 6 5 6 5 6 5 6 6 8 6 6 5 5 6 5 5 5 5 6 7 6 6 5 6 5 6 6 5 6 5 5 6 6 5 5 6
 5 7 5 6 5 6 6 6 5 6 6 6 5 5 5 5 6 5 6 5 5 5 5 5 5 5 5 5 5 5 5 5 5 7 5 6 6
 6 5 6 5 5 5 5 6 5 5 5 5 6 6 5 6 5 5 5 5 5 5 6 6 6 6 6 6 5 6 6 6 6 7 6 5 6
 6 5 6 6 6 6 5 5 5 5 6 5 5 6 6 6 6 6 5 5 5 6 5 7 5 6 5 6 5 6 7 6 7 6 5 6 5
 7 6 7 6 6 5 5 6 6 6 6 5 5 5 6 5 6 5 6 7 6 5 5 6 5 5 5 5 6 5 5 6 6 5 5 6 6
 6 5 6 6 6 7 6 5 5 6 7 5 5 6 6 6 6 5 6 6 5 7 6 5 6 5 7 6 6 6 6 6 7 6 6 5 5
 5 5 6 7 6 6 5 5 5 5 5 7 6 6 6 5 5 6 6 5 5 6 7 5 6 5 5 6 6 7 6 5 5 6 7 6 6
 5 5 6 7 6 5 5 5 5 5 5 5 5 5 6 5 6 6 6 7 5 6 6 6 6 5 5 5 5 6 6 6 7 6 6 5 5
 6 6 6 6 6 5 6 4 5 6 6 5 5 6 6 5 5 5 5 6 6 6 5 5 5 6 5 7 5 5 5 7 5 7 5 5 5
 5 5 6 5 5 6 5 5 6 5 7 6 6 6 6 5 5 7 6 6 6 5 6 5 7 6 5 7 6 5 5 5 6 5 5 5 5
 5 6 5 5 5 6 7 6 5 5 5 6 6 5 5 5 6 7 5 6 5 5 6 5 5 5 5 6 5 6 6 5 5 6 5 7 6
 6 6 5 5 5 5 6 6 5 5 5 6 5 6 6 5 6 6 6 6 5 5 5 4 5 6 6 6 5 6 6 5 5 6 5 6 5
 6 5 6 5 5 5 5 7 6 6 5 6 

In [111]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, predictions))

[[  0   0   4   1   1   0]
 [  0   0  11   9   0   0]
 [  0   0 185  88   3   0]
 [  0   0  83 155  12   0]
 [  0   0   9  49  17   0]
 [  0   0   0  12   1   0]]


In [112]:
print(classification_report(y_test, grid_predictions))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         6
           4       0.00      0.00      0.00        20
           5       0.65      0.75      0.70       276
           6       0.54      0.59      0.57       250
           7       0.49      0.32      0.39        75
           8       0.00      0.00      0.00        13

    accuracy                           0.59       640
   macro avg       0.28      0.28      0.28       640
weighted avg       0.55      0.59      0.57       640



C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [113]:
from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel = 'rbf', C = 1)
scores = cross_val_score(clf, x, y, cv = 5)
scores

C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoi

array([0.51242236, 0.52024922, 0.47663551, 0.48427673, 0.47003155])

In [114]:
scores.mean()

0.4927230741504026