## Predict the Class Performance

Problem Statement
You are supposed to predict the performance of the student. 
The student are measured on different attribute standard 
and their performance are marked in the class column as Low, high and medium.
Do the necessary preprcessing and develop a model using an MLP classifier.

Hint: Preprocessing is mandate for the model to work. 

In [118]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier

In [119]:
df = pd.read_csv('D:/Study/MCA/5thSem/ML/Dataset-ISA2.csv')
df.head()

gender NationalITy PlaceofBirth     StageID GradeID SectionID Topic  \
0      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
1      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
2      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
3      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
4      M          KW       KuwaIT  lowerlevel    G-04         A    IT   

  Semester Relation  raisedhands  VisITedResources  AnnouncementsView  \
0        F   Father           15                16                  2   
1        F   Father           20                20                  3   
2        F   Father           10                 7                  0   
3        F   Father           30                25                  5   
4        F   Father           40                50                 12   

   Discussion ParentAnsweringSurvey ParentschoolSatisfaction  \
0          20                   Yes                     Good   
1          25                   Yes                     Good   
2          30                    No                      Bad   
3          35                    No                      Bad   
4          50                    No                      Bad   

  StudentAbsenceDays Class  
0            Under-7     M  
1            Under-7     M  
2            Above-7     L  
3            Above-7     L  
4            Above-7     M

In [120]:
df['Class'] = [2 if i == 'L' else 1 if i == 'M' else 0 for i in df['Class']]
df.head()

gender NationalITy PlaceofBirth     StageID GradeID SectionID Topic  \
0      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
1      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
2      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
3      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
4      M          KW       KuwaIT  lowerlevel    G-04         A    IT   

  Semester Relation  raisedhands  VisITedResources  AnnouncementsView  \
0        F   Father           15                16                  2   
1        F   Father           20                20                  3   
2        F   Father           10                 7                  0   
3        F   Father           30                25                  5   
4        F   Father           40                50                 12   

   Discussion ParentAnsweringSurvey ParentschoolSatisfaction  \
0          20                   Yes                     Good   
1          25                   Yes                     Good   
2          30                    No                      Bad   
3          35                    No                      Bad   
4          50                    No                      Bad   

  StudentAbsenceDays  Class  
0            Under-7      1  
1            Under-7      1  
2            Above-7      2  
3            Above-7      2  
4            Above-7      1

In [121]:
x = df[['raisedhands', 'VisITedResources', 'AnnouncementsView', 'Discussion']]
y = df['Class']
print(x.shape)
print(y.shape)

(480, 4)
(480,)


In [122]:
x.head()

raisedhands  VisITedResources  AnnouncementsView  Discussion
0           15                16                  2          20
1           20                20                  3          25
2           10                 7                  0          30
3           30                25                  5          35
4           40                50                 12          50

In [123]:
from sklearn.model_selection import train_test_split

In [124]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)
print(x_train.shape)
print(x_test.shape)

(384, 4)
(96, 4)


In [125]:
from sklearn.preprocessing import StandardScaler

In [126]:
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
scaler.fit(x_test)
x_test = scaler.transform(x_test)

In [127]:
nn = MLPClassifier()
nn.fit(x_train, y_train)

C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100,), learning_rate='constant',
              learning_rate_init=0.001, max_iter=200, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [128]:
pred = nn.predict(x_test)

In [129]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [130]:
acc = accuracy_score(y_test, pred)
acc

0.6041666666666666

In [131]:
print(confusion_matrix(y_test, pred))

[[19 14  1]
 [ 6 23  7]
 [ 0 10 16]]


In [132]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.76      0.56      0.64        34
           1       0.49      0.64      0.55        36
           2       0.67      0.62      0.64        26

    accuracy                           0.60        96
   macro avg       0.64      0.60      0.61        96
weighted avg       0.63      0.60      0.61        96



In [133]:
nn.get_params()

{'activation': 'relu',
 'alpha': 0.0001,
 'batch_size': 'auto',
 'beta_1': 0.9,
 'beta_2': 0.999,
 'early_stopping': False,
 'epsilon': 1e-08,
 'hidden_layer_sizes': (100,),
 'learning_rate': 'constant',
 'learning_rate_init': 0.001,
 'max_iter': 200,
 'momentum': 0.9,
 'n_iter_no_change': 10,
 'nesterovs_momentum': True,
 'power_t': 0.5,
 'random_state': None,
 'shuffle': True,
 'solver': 'adam',
 'tol': 0.0001,
 'validation_fraction': 0.1,
 'verbose': False,
 'warm_start': False}

In [134]:
from sklearn.model_selection import GridSearchCV

In [135]:
grid = {
    'alpha': [0.1, 1, 0.01, 0.001],
    'activation': ['relu', 'tanh'],
    'hidden_layer_sizes': ((15, 12), (15,15)),
    'max_iter': [200, 100, 150]
}

In [136]:
grid_nn = GridSearchCV(nn, param_grid = grid)

In [137]:
grid_nn.fit(x_train, y_train)

C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\neural_net

C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\neural_net

C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\neural_net

C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\neural_net

C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (150) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\neural_net

C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (150) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (150) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (150) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Vijaykumar R Pai.LAPTOP-C26T1P75\AppData\Roaming\Python\Python37\site-packages\sklearn\model_sele

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=MLPClassifier(activation='relu', alpha=0.0001,
                                     batch_size='auto', beta_1=0.9,
                                     beta_2=0.999, early_stopping=False,
                                     epsilon=1e-08, hidden_layer_sizes=(100,),
                                     learning_rate='constant',
                                     learning_rate_init=0.001, max_iter=200,
                                     momentum=0.9, n_iter_no_change=10,
                                     nesterovs_momentum=True, power_t=0.5,
                                     random_state=None, shuffle=True,
                                     solver='adam', tol=0.0001,
                                     validation_fraction=0.1, verbose=False,
                                     warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'activation': ['relu', 'tanh'],
    

In [138]:
pred1 = grid_nn.predict(x_test)

In [139]:
accuracy_score(y_test, pred)

0.6041666666666666

In [140]:
grid_nn.best_params_

{'activation': 'relu',
 'alpha': 0.001,
 'hidden_layer_sizes': (15, 15),
 'max_iter': 200}